site_name: Acceso a Datos DAM

nav:
  - Inicio: index.md
  - Unidades:
    - UD1 - Programaci贸n en el entorno Kotlin.: unidades/ud01/ud01.md
    - UD2 - Persistencia en ficheros:
      - Introducci贸n: unidades/ud02/introduccion.md
      - Ficheros y directorios: unidades/ud02/ficheros_directorios.md
      - Ficheros de texto: unidades/ud02/ficheros_texto.md
      - Ficheros de intercambio: unidades/ud02/ficheros_intercambio.md
      - Ficheros binarios: unidades/ud02/ficheros_binarios.md
      - Ficheros de acceso aleatorio: unidades/ud02/ficheros_acceso_aleatorio.md
      - Documentaci贸n final: unidades/ud02/documentacion_final.md

repo_url: https://github.com/jmabadlopez/acceso_datos
repo_name: jmabadlopez/acceso_datos

theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  icon: fontawesome/brands/mastodon
  hljs_languages:
    - python
    - java
    - c
    - kotlin
  features:
    - navigation.top
    - optimize
    - content.code.copy
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: amber
      accent: amber

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: amber
      accent: amber
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

# plugins:
#   - to-pdf:
#       author: Jos茅 Manuel Abad L贸pez
#       copyright:  Creative Commons CC BY-SA 4.0 2025
#       cover_title: Acceso a Datos
#       cover_subtitle: 2潞 DAM
#       toc_title: "Contenidos"
#       toc_level: 3
#       output_path: ../public/libro.pdf